apiVersion: v1
kind: ConfigMap
data:
  MEMCACHED_HOST: memcached.memcached.svc.cluster.local
  REDIS_URL: redis.redis.svc.cluster.local
  SECRET_KEY_BASE: be539ada6314748600795b0d3e758fa21ffb5b50db8fc0f41025178e9d26525d196ed968e7cde9db9c711128f9987e4ddcb912eacce3a6c5d32baf01c9ec6eec
  RAILS_LOG_TO_STDOUT: "true"
metadata:
  name: decidim-app-production-config
  namespace: decidim
---
apiVersion: v1
kind: ConfigMap
data:
  MEMCACHED_HOST: memcached.memcached.svc.cluster.local
  REDIS_URL: redis.redis.svc.cluster.local
  SECRET_KEY_BASE: be539ada6314748600795b0d3e758fa21ffb5b50db8fc0f41025178e9d26525d196ed968e7cde9db9c711128f9987e4ddcb912eacce3a6c5d32baf01c9ec6eec
  RAILS_LOG_TO_STDOUT: "true"
metadata:
  name: decidim-app-staging-config
  namespace: decidim
